import{S as u,i}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const m="46105418-b730233871b128ee828c4e337",d="https://pixabay.com/api/";async function p(n){const o=`${d}?key=${m}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const e=await fetch(o);if(!e.ok)throw new Error("Failed to fetch images");const r=await e.json();if(r.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return r.hits}catch(e){return console.error(e.message),alert(e.message),[]}}let c;function f(n,o){o.innerHTML="";const e=n.map(r=>`
    <a href="${r.largeImageURL}" class="gallery__item" data-lightbox="image">
      <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </a>
  `).join("");o.insertAdjacentHTML("beforeend",e),c?c.refresh():c=new u(".gallery__item",{captionsData:"alt",captionDelay:250})}const g=document.getElementById("searchForm"),y=document.getElementById("gallery"),l=document.getElementById("loader");g.addEventListener("submit",async function(n){n.preventDefault();const o=document.getElementById("searchInput").value.trim();if(o===""){i.warning({title:"Warning",message:"Please enter a search query",position:"topRight"});return}l.style.display="block";try{const e=await p(o);e.length>0?(f(e,y),i.success({title:"Success",message:`Found ${e.length} images for "${o}"`,position:"topRight"})):i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch(e){i.error({title:"Error",message:e.message,position:"topRight"})}finally{l.style.display="none"}});
//# sourceMappingURL=index.js.map
